services:
  shared-postgres:
    image: postgres:15-alpine
    container_name: shared_db_server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: auth,movie,watch
    volumes:
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  auth-service:
    build: ./AuthService
    container_name: auth_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shared-postgres:5432/${POSTGRES_AUTHDB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      shared-postgres:
        condition: service_healthy

  movie-service:
    build: ./movieservice
    container_name: movie_backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shared-postgres:5432/${POSTGRES_MOVIEDB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      shared-postgres:
        condition: service_healthy

  watches-service:
    build: ./watchservice
    container_name: watch_backend
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shared-postgres:5432/${POSTGRES_WATCHLISTDB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MOVIE_SERVICE_URL: ${MOVIE_SERVICE_URL}
    depends_on:
      shared-postgres:
        condition: service_healthy
volumes:
  pgadmin_data:
  postgres_data:
